name: Unit Tests + Linters

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: '~2.9.0'
          cache: true
      - name: Cache local node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('deno.lock') }}
      - name: Install dependencies
        run: deno install --frozen
      - name: Run unit tests
        run: deno task test
      - name: Run linters
        run: deno task lint
